# Generated by Django 5.1.8 on 2026-04-29 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('organizations', '0001_initial'),
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='individual_targets',
            field=models.ManyToManyField(blank=True, help_text='Used when Target Type is "Individual Selection"', related_name='individual_campaigns', to='targets.target'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_department',
            field=models.ForeignKey(blank=True, help_text='Used when Target Type is "By Department"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_campaigns', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_group',
            field=models.ForeignKey(blank=True, help_text='Used when Target Type is "By Target Group"', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_campaigns', to='targets.targetgroup'),
        ),
        migrations.AddField(
            model_name='abtest',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_targets', to='targets.target'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaigns.senderprofile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.template'),
        ),
        migrations.AddField(
            model_name='abtest',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ab_tests', to='campaigns.template'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigntarget',
            unique_together={('campaign', 'target')},
        ),
    ]
