# Generated by Django 5.1.8 on 2026-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='finish_date',
            field=models.DateTimeField(blank=True, help_text='Optional: tracking links auto-disable after this date/time. Leave blank to disable only via the Finish action.', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('finished', 'Finished')], default='draft', max_length=15),
        ),
    ]
