# Generated by Django 5.1.8 on 2026-05-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_finished_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Leave blank to send manually without auto-scheduling.', null=True),
        ),
    ]
