# Generated by Django 5.1.8 on 2026-05-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_scheduled_date_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, help_text='Optional internal notes or campaign description.'),
        ),
    ]
