# Generated by Django 5.1.8 on 2026-05-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, help_text='Optional internal notes or campaign description.', null=True),
        ),
    ]
