# Generated by Django 5.1.8 on 2026-05-15 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_description_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='abtest',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Override sender identity for this variant. Leave blank to use campaign sender.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ab_tests', to='campaigns.senderprofile'),
        ),
        migrations.AddField(
            model_name='abtest',
            name='subject_override',
            field=models.CharField(blank=True, help_text='Override just the email subject. Leave blank to use the template subject.', max_length=255),
        ),
    ]
