# Generated by Django 5.1.8 on 2026-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_abtest_subject_sender'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='excluded_targets',
            field=models.ManyToManyField(blank=True, help_text='Targets explicitly excluded from receiving this campaign.', related_name='excluded_campaigns', to='targets.target'),
        ),
    ]
