# Generated by Django 5.1.8 on 2026-05-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_excluded_targets'),
        ('organizations', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='target_department',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_group',
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_departments',
            field=models.ManyToManyField(blank=True, help_text='Used when Target Type is "By Department". Select one or more departments.', related_name='department_campaigns', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_groups',
            field=models.ManyToManyField(blank=True, help_text='Used when Target Type is "By Target Group". Select one or more groups.', related_name='group_campaigns', to='targets.targetgroup'),
        ),
    ]
