# Generated by Django 5.1.8 on 2026-04-29 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('opened', 'Opened'), ('clicked', 'Clicked'), ('submitted', 'Submitted'), ('reported', 'Reported')], max_length=15)),
                ('event_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.TextField(blank=True)),
                ('submitted_data', models.JSONField(blank=True, null=True)),
                ('campaign_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='campaigns.campaigntarget')),
            ],
            options={
                'db_table': 'interactions',
                'indexes': [models.Index(fields=['campaign_target', 'event_type'], name='interaction_campaig_c4b0f8_idx'), models.Index(fields=['event_timestamp'], name='interaction_event_t_8e9167_idx')],
            },
        ),
    ]
